"""empty message

Revision ID: 8604af8b61c7
Revises: cb625c026055
Create Date: 2024-04-04 00:57:16.951751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8604af8b61c7'
down_revision = 'cb625c026055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_seller_name_fkey', type_='foreignkey')
        batch_op.drop_column('seller_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('products_seller_name_fkey', 'users', ['seller_name'], ['user_name'])

    # ### end Alembic commands ###
