"""empty message

Revision ID: 8da08588fd6a
Revises: 8604af8b61c7
Create Date: 2024-04-04 01:08:52.910255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da08588fd6a'
down_revision = '8604af8b61c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_seller_id_fkey', type_='foreignkey')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('products_seller_id_fkey', 'users', ['seller_id'], ['id'])

    # ### end Alembic commands ###
