"""empty message

Revision ID: cb625c026055
Revises: ca7206a7077d
Create Date: 2024-04-04 00:52:18.238027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb625c026055'
down_revision = 'ca7206a7077d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_name', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['seller_name'], ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('seller_name')

    # ### end Alembic commands ###
