"""empty message

Revision ID: f9c7a0d88326
Revises: 5820d59190ef
Create Date: 2024-04-11 00:17:05.148131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c7a0d88326'
down_revision = '5820d59190ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('items_to_view', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('appointment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('items_to_view', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='appointment_pkey')
    )
    op.drop_table('appointments')
    # ### end Alembic commands ###
